name: Test code examples
on: [push, pull_request]
jobs: 
  tests:
    runs-on: ubuntu-18.04
    name: test examples
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: test scripts
        run: |
          python examples/01-specific-heat-peak.py
          python examples/02-fisher-matrix.py
          python examples/03-endtoend-vmc.py